name: Run Function Every 20 Hours

on:
  schedule:
   - cron: '0 0,12 * * *'

jobs:
  run_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg

      - name: Install Node.js and npm
        run: |
          sudo apt-get install -y nodejs npm

      - name: Check if npm is installed
        run: npm --version

      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install -y cf-cli

      - name: Login to CF
        run: cf login -a https://api.cf.us10-001.hana.ondemand.com -u mevlutcan.maden@solviads.com -p M.maden37

      - name: Reset front
        run: cf start mdnViewPlugins

      - name: Reset Backend
        run: cf start demoBackendServices
