name: Run Start Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install CF CLI
      run: |
        sudo apt-get update
        sudo apt-get install cf-cli
     
    - name: cd
      run: cd ViewPodPlugin
    
    - name: Run Start Script
      run: cf push
