name: CF Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CF CLI
      uses: cloudfoundry/github-actions/setup-cf@v1
      with:
        api-url: https://api.cf.us10-001.hana.ondemand.com
        username: mevlutcan.maden@solviads.com
        password: M.maden37

    - name: Login to Cloud Foundry
      run: |
        cf login

    - name: Push application to Cloud Foundry
      run: cf push
